apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-app-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app-api
  template:
    metadata:
      labels:
        app: hello-app-api
    spec:
      containers:
        - name: hello-app-api
          image: longthanhle1122/hello-app-api:{{ run_id }}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - containerPort: 3000
